## This is the minimal environment description to run the DADA2 pipeline, except
## that DADA2 itself is installed in a separate step (see INSTALL.txt).  Below
## note that R version 4.1 is specified because that is named on the dada2
## Bioconductor page
##    https://bioconductor.org/packages/release/bioc/html/dada2.html
## for dada2 v3.13.  This page seems more current than Ben's DADA2 instructions:
##    https://benjjneb.github.io/dada2/dada-installation.html
## for dada2 v3.11, which requires R v.4.0.
name: DADA2_nifH
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - cutadapt
  - hmmer
  - r-essentials=4.1
  - r-base=4.1
