## This is the minimal environment description to run the DADA2 pipeline, except that DADA2 itself
## is installed in a separate step using R (see INSTALL.txt).  Below I specify R version 4.1 because
## I have used v4.1 the most with the pipeline and it is the most recent version that installed
## successfully using the directions in INSTALL.txt (last verified March 21, 2023).
##
## Version information is available from the Bioconductor DADA2 installation page (currently v4.2):
##    https://bioconductor.org/packages/release/bioc/html/dada2.html
## Also helpful is Benjamin Callahan's DADA2 installation page:
##    https://benjjneb.github.io/dada2/dada-installation.html
## However, it is at v3.11 for DADA2 and v4.0 for R.
##
name: DADA2_nifH
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - cutadapt
  - hmmer
  - fraggenescan
  - r-essentials=4.1
