## Copyright (C) 2023 Jonathan D. Magasin
##
## This file describes the conda environment DADA2_nifH for running the DADA2 nifH pipeline as well
## as the ancillary scripts. You should use either this .yml file or the minimal one in
## environment_DADA2_nifH.yml.  Please see INSTALL.txt
##
## The pipeline and ancillary tools were developed mainly using DADA2 version 1.20.0 (and R v4.1.3).
## The package verions below were used when creating the nifH ASV database described in Morando and
## Magasin et al., 2024 in Earth System Science Data.
##
name: DADA2_nifH
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  # Core pipeline
  - r-base             =4.3.3
  - bioconductor-dada2 =1.30.0
  - r-vegan            =2.6_8
  - cutadapt           =4.9
  - fraggenescan       =1.31
  - hmmer              =3.4
  
  # Ancillary scripts           Needed by:
  - r-digest           =0.6.37 #  assignAUIDs2ASVs.R
  - fastqc             =0.12.1 #  do_fastqc.sh
  - vsearch            =2.28.1 #  check_chimera_denovo.sh
  - blast              =2.16.0 #  check_nifH_contaminants.sh, classifyNifH.sh, blast{nARB2017,xGenome879}.sh
  - biopython          =1.84   #  assignNifHclustersToNuclSeqs.sh
  - mafft              =7.526  #  assignNifHclustersToNuclSeqs.sh
